FROM debian:bullseye as certs
RUN apt update && apt install -y ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY apt-proxy /usr/bin/apt-proxy
EXPOSE 3142/tcp
ENTRYPOINT ["/usr/bin/apt-proxy"]